### ISSUE TITLE
Cannot read property 'outcomeHeaderHash' of undefined

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#131]
Cannot read property 'outcomeHeaderHash' of undefined

TypeError: Cannot read property 'outcomeHeaderHash' of undefined
    at file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:351:377477
    at Array.forEach (<anonymous>)
    at Yd (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:351:377350)
    at Nd (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:351:378984)
    at n (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:351:422562)
    at file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:351:422572
    at us (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:309:83260)
    at Lc (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:309:102452)
    at t.unstable_runWithPriority (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:317:3844)
    at Ko (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/app.js:309:45048)

**Comment by Connoropolous** [comment]
closing because we don't know how to reproduce.
