### ISSUE TITLE
Crash after viewing comments section

### ISSUE THREAD

**Issue by var-che** [lightningrodlabs/acorn#140]
I have posted comment from my different machine on speciific outcome. 
On this machine, I just wanted to view that comment that got posted. This is what I got

Cannot read property 'firstName' of undefined

TypeError: Cannot read property 'firstName' of undefined
    at file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:359:114730
    at Qa (file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:309:57951)
    at ws (file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:309:104333)
    at xc (file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:309:96859)
    at _c (file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:309:96784)
    at fc (file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:309:93807)
    at file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:309:45339
    at t.unstable_runWithPriority (file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:317:3844)
    at Ko (file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:309:45048)
    at Xo (file:///tmp/.mount_Acorn-zq5Ce1/resources/app.asar/web/app.js:309:45284)

**Comment by pegahvaezi** [comment]
Hi @var-che would you be able to try the latest release (v1.1.0-alpha) and let us know if you still face the same issue with the Comments section?
