### ISSUE TITLE
Linux appimage stop with loading ..... state

### ISSUE THREAD

**Issue by rbolog** [lightningrodlabs/acorn#151]
Hi,
I tried acorn from appimage under linux and it stay with loading ... state

Acorn version 1.0.4 alpha

my system:

Operating System: Manjaro Linux
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.14-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × Intel® Core™ i7-10870H CPU @ 2.20GHz
Memory: 31.2 Gio of RAM
Graphics Processor: Mesa Intel® UHD Graphics

regards

**Comment by Connoropolous** [comment]
Are you starting it up from the command line? Does it produce any more logs that could be useful?

**Comment by rbolog** [comment]
No I started, using AppImage launcher. But I did and please find the report and the output:

[report](https://ipfs.infura-ipfs.io/ipfs/QmTcAvFGC3ZaYZ73yf24B9Pox72ak3UQyJux3APXk1XySh)

```
(acorn:3020): Gtk-WARNING **: 09:19:42.511: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
holochain > Looking for passphrase piped to stdin
holochain > Found passphrase, continuing...
holochain > 1
holochain stderr err > Well, this is embarrassing.

holochain-runner had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-56b88191-eb87-4ec1-aeea-3e7cab3240eb.toml". Submit an issue or email with the subject of "holochain-runner Crash Report" and include the report as an attachment.

- Authors: Connor Turland 

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

an unhandled error occurred: Error: Well, this is embarrassing.

holochain-runner had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-56b88191-eb87-4ec1-aeea-3e7cab3240eb.toml". Submit an issue or email with the subject of "holochain-runner Crash Report" and include the report as an attachment.

- Authors: Connor Turland 

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

    at Socket.<anonymous> (/tmp/.mount_Acorn-0IRf2q/resources/app.asar/node_modules/@sprillow-connor/electron-holochain/dist/src/holochain.js:192:33)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
holochain > 
holochain-runner closed with code:  101
```

**Comment by HexaField** [comment]
i am also seeing this. the report file contains the following: 
```

**Comment by Connoropolous** [comment]
Hi @rbolog and @HexaField thanks for the reports! 
I am going to take a look into the issue

**Comment by Connoropolous** [comment]
@weswalla this is the reported version of the issue.

**Comment by Connoropolous** [comment]
@zippy we are working on your issue here

**Comment by Connoropolous** [comment]
I think `electron-holochain` is actually the place we want to intervene right now

**Comment by rbolog** [comment]
Hello,
The v1.1.0-alpha solve the issue. Tested using Manjaro.

Thanks

**Comment by Connoropolous** [comment]
Oh, well that's good. It must have been a separate issue from the one reported by @zippy and @HexaField . I've just opened up a new ticket to track that. #160
