### ISSUE TITLE
Error: `main-app` already installed

### ISSUE THREAD

**Issue by pdaoust** [lightningrodlabs/acorn#162]
**Release:** 1.1.0-alpha
**Build:** AppImage for Ubuntu 22.04 / AMD64

**Problem:** When I open Acorn a second time, it errors with the following error in the console: `AppAlreadyInstalled("main-app")`. Full log pasted below.

**Steps to reproduce:**

1. Install and run Acorn
2. Get it all set up, maybe create a project or two; not sure
3. Close Acorn
4. Open it again

**Comment by pdaoust** [comment]
```
holochain > ###HOLOCHAIN_SETUP###
holochain > ###ADMIN_PORT:1235###
holochain > ###HOLOCHAIN_SETUP_END###
holochain > DATASTORE_PATH: /home/paul/.config/acorn/databases-3
holochain >  KEYSTORE_URL: unix:///home/paul/.config/acorn/keystore-3/socket?k=g6Tv4UFyaw2Q_CDXgyfq5odpveSjGsDdh_yXfPHj-hQ
holochain >            UID: None
holochain > Recognized a keypair, using that...
holochain > There is no app installed, so starting fresh...
holochain > continuing with the installation...
holochain > 4
holochain stderr err > Sep 09 16:45:46.982 ERROR holochain_runner::embedded_runner: Conductor returned an error while using a ConductorApi: AppAlreadyInstalled("main-app")
FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        explicit panic,
    ),
    location: Location {
        file: "src/embedded_runner.rs",
        line: 116,
        col: 17,
    },
    can_unwind: true,
}

an unhandled error occurred: Error: Sep 09 16:45:46.982 ERROR holochain_runner::embedded_runner: Conductor returned an error while using a ConductorApi: AppAlreadyInstalled("main-app")
FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        explicit panic,
    ),
    location: Location {
        file: "src/embedded_runner.rs",
        line: 116,
        col: 17,
    },
    can_unwind: true,
}

    at Socket.<anonymous> (/tmp/.mount_Acorn-Ie5uE2/resources/app.asar/node_modules/@sprillow-connor/electron-holochain/dist/src/holochain.js:192:33)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by Connoropolous** [comment]
@pdaoust did you have "real" projects you were working on, or would you be fine to reset your application data?

https://docs.acorn.software/troubleshooting/clea

**Comment by Connoropolous** [comment]
@pdaoust would love to help you get this resolved

**Comment by Connoropolous** [comment]
Closing per lack of response, we can re-oprn it if the issue is persistent on a newer version of Acorn
