### ISSUE TITLE
Sorry... Acorn has crashed

### ISSUE THREAD

**Issue by Seoste** [lightningrodlabs/acorn#19]
Hey,

I got to try Acorn with my Ubuntu. First time I gave my details, but after getting to next stage it crashed. Now it just says it has crashed and reload and restart does not make things any better.

The "stack trace" says...

"Cannot read property 'toUpperCase' of undefined

TypeError: Cannot read property 'toUpperCase' of undefined"

Just to let you know, hope to get it up and running!

**Comment by Connoropolous** [comment]
Hi!

You must have gotten into a corrupted state somehow. 

Do you use command line?

**Comment by Seoste** [comment]
Hey,

No idea how I got to that stage, but can not get out.

Not using command line. I just downloaded AppImage and thats it.

Here is whole details it shows:

Cannot read property 'toUpperCase' of undefined

TypeError: Cannot read property 'toUpperCase' of undefined
    at va (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:351:240561)
    at Za (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:309:57951)
    at ws (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:309:104333)
    at xl (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:309:96859)
    at bl (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:309:96784)
    at fl (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:309:93807)
    at file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:309:45339
    at t.unstable_runWithPriority (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:317:3844)
    at Go (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:309:45048)
    at Xo (file:///tmp/.mount_Acorn-IKdE7Y/resources/app.asar/web/main.js:309:45284)

**Comment by pegahvaezi** [comment]
We are closing this as we haven't heard back. Hope you try downloading and using a recent release of Acorn as the product has vastly improved since that release from 2021.
