### ISSUE TITLE
Switching between projects crashes Acorn.

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#199]
v2.1.0-alpha

When you switch between projects Acorn crashes.
https://user-images.githubusercontent.com/65631811/199151842-4ff8d216-22ee-4139-9c9c-6c2e4ff62afc.mp4

Cannot read properties of undefined (reading 'actionHash')

TypeError: Cannot read properties of undefined (reading 'actionHash')
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:106534:20
    at Array.map (<anonymous>)
    at MultiEditBar_component_MultiEditBar (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:106532:23)
    at oh (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:77812:146)
    at di (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:77834:309)
    at Rj (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:77922:406)
    at Qj (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:77905:265)
    at Kj (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:77905:194)
    at yj (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:77898:172)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:77782:115

**Comment by Connoropolous** [comment]
👋 

is it happening every time you switch between projects?

**Comment by TechSupport26** [comment]
Yes, it is. You can go the the main menu and reenter the same project with no crash,

**Comment by Connoropolous** [comment]
Kk. Is it preventing you from accessing your projects completely? or are you still able to for now?

We will try to reproduce it.

**Comment by TechSupport26** [comment]
I just hit reload and it's fine.

https://user-images.githubusercontent.com/65631811/199152952-f7fd87c2-63bb-463a-98f8-0478cf78fc2e.mp4

**Comment by Connoropolous** [comment]
I can reproduce this. We will ship an update tomorrow to fix it. Easy.

**Comment by Connoropolous** [comment]
fixed in the new https://github.com/lightningrodlabs/acorn/releases/tag/v2.1.1-alpha !

**Comment by TechSupport26** [comment]
I am unsure about what is causing this to happen.
When there are enough cards in a project they will not be drawn/rendered depending on how far you zoom in (or if there are enough cards they will not render at all and you have to zoom out). The card branches are still visible and when the mouse is over a card the outcome statement will come up. This happens on 2 of my projects. they have 

https://user-images.githubusercontent.com/65631811/199459014-52725dea-b2b2-40ee-82b6-123297babfbc.mp4

This crash can be delayed if you switch to another project. It only works on some projects (I have no idea why).

Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:91960:21
    at draw (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:91488:5)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:91928:13
    at draw (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:91488:5)
    at drawAvatar (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:91878:12)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:92007:17
    at Array.forEach (<anonymous>)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:91998:21
    at draw (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:91488:5)
    at drawAssignees (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:91996:9)
