### ISSUE TITLE
App crashed while deleting a connector

### ISSUE THREAD

**Issue by adamth0mps0n** [lightningrodlabs/acorn#20]
I was deleting a connector by highlighting it an using the backspace when things crashed.. 
See crash report below. 
Cannot read property 'content' of undefined

TypeError: Cannot read property 'content' of undefined
    at hp (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:358:59174)
    at Za (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:309:57951)
    at Fi (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:309:66806)
    at ws (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:309:105552)
    at xl (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:309:96859)
    at bl (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:309:96784)
    at fl (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:309:93807)
    at file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:309:45339
    at t.unstable_runWithPriority (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:317:3844)
    at Go (file:///tmp/.mount_Acorn-yLaCAe/resources/app.asar/web/main.js:309:45048)

**Comment by Connoropolous** [comment]
thanks for reporting! 

we will attempt to reproduce the issue, and proceed to fix.

**Comment by pegahvaezi** [comment]
@adamth0mps0n have you been able to replicate this issue in the latest release (v1.0.2-alpha)?

**Comment by adamth0mps0n** [comment]
No.
The new version has been behaving itself.
