### ISSUE TITLE
can't run version 2.1.1-alpha

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#220]
This is what the start-up looks like
```
holochain > Looking for passphrase piped to stdin
holochain > Found passphrase, continuing...
holochain > 1
holochain stderr err > WARNING: running without local db encryption

an unhandled error occurred: Error: WARNING: running without local db encryption

    at Socket.<anonymous> (C:\Users\zephd\AppData\Local\Programs\acorn\resources\app.asar\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
holochain > WARNING: running without local db encryption
holochain > # lair-keystore connection_url # named-pipe:\\.\pipe\24w39KvTAyKpJiY5d34lg?k=fJwfC-tVlWfbCamzM5SSGM9W8xnkvVijVqRDm0nsRHI #
holochain > # lair-keystore running #
holochain >
holochain > ###HOLOCHAIN_SETUP###
holochain > ###ADMIN_PORT:1235###
holochain > ###HOLOCHAIN_SETUP_END###
holochain > DATASTORE_PATH: C:\Users\zephd\AppData\Roaming\acorn\databases-4
holochain > KEYSTORE_PATH: Some("C:\\Users\\zephd\\AppData\\Roaming\\acorn\\keystore-3")
holochain > NETWORK_SEED: None
holochain > Recognized a keypair, using that...
holochain > An existing configuration and identity was found, using that.
holochain >      APP_WS_PORT: 8889
holochain > INSTALLED_APP_ID: acorn-project-186832-uid-registrar-despise-applaud-embody-pouch
holochain > HOLOCHAIN_RUNNER_IS_READY
holochain > 7
holochain > Dec 12 06:06:55.629 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
holochain > Dec 12 06:07:31.453 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
holochain > Dec 12 06:07:41.435 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
holochain stderr err > Dec 12 06:07:46.299 ERROR kitsune_p2p::gossip::sharded_gossip: Tgt expired Cert(HIXMoi..AXfigg)

an unhandled error occurred: Error: Dec 12 06:07:46.299 ERROR kitsune_p2p::gossip::sharded_gossip: Tgt expired Cert(HIXMoi..AXfigg)

    at Socket.<anonymous> (C:\Users\zephd\AppData\Local\Programs\acorn\resources\app.asar\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
holochain > Dec 12 06:07:51.442 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
holochain > Dec 12 06:08:01.458 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
holochain > Dec 12 06:08:11.442 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
holochain > Dec 12 06:08:21.438 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
holochain > Dec 12 06:08:31.410 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
holochain > Dec 12 06:08:41.397 DEBUG wasm_trace: projects:happ/zomes/projects/src/lib.rs:216 Received remote signal RealtimeInfo(RealtimeInfoSignal { agent_pub_key: HoloHashB64(AgentPubKey(uhCAk-yzwxMPf7JR8kDiWJSsFy5aQTMcre1KzKZwwBBdSkarJsVFm)), project_id: "132,45,36,77,104,13,7,32,250,68,103,98,46,198,227,195,252,45,141,224,14,52,102,37,182,55,226,149,210,184,100,77,187,160,144,165,60,190,120[:cell_id_divider:]132,32,36,251,44,240,196,195,223,236,148,124,144,56,150,37,43,5,203,150,144,76,199,43,123,82,179,41,156,48,4,23,82,145,170,201,177,81,102", outcome_being_edited: None, outcome_expanded_view: Some(HoloHashB64(ActionHash(uhCkktkTiMHbtAfFfI-Zd1szd4WpG9iDhFCpFKHtpyU4rdUj464TI))) })
[21624:1212/060843.433:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is
```
And if I force refresh

```
holochain stderr err > Dec 12 06:10:41.398 ERROR holochain::conductor::interface::websocket: error emitting signal err=WebsocketError(Shutdown)

an unhandled error occurred: Error: Dec 12 06:10:41.398 ERROR holochain::conductor::interface::websocket: error emitting signal err=WebsocketError(Shutdown)

    at Socket.<anonymous> (C:\Users\zephd\AppData\Local\Programs\acorn\resources\app.asar\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

_Originally posted by @TechSupport26 in https://github.com/lightningrodlabs/acorn/discussions/26#discussioncomment-4372880_

**Comment by Connoropolous** [comment]
Please describe the circumstances under which you are trying to run it... 

Which operating system are you on? Is this the same computer as you have been running it typically? Were you previously running Acorn on this computer, and suddenly this started happening? Did you change something else in your environment when it stopped working?

**Comment by TechSupport26** [comment]
I am on windows 10 and am using the same computer. This only just started to happen. I don't believe I did anything that may have broken Acorn.

I try to run Acorn and it just gets stuck on collecting your acorns.

Let me know if you have any more questions.
Thanks.

**Comment by Connoropolous** [comment]
Thanks for the info. 

If you know how, can you open the "Dev Tools" -> "Console" and screenshot or copy-paste whatever is there, in case it reveals the issue. I am not seeing the issue in any of the logs provided so far.

**Comment by TechSupport26** [comment]
I have already exported my projects so I can just move on to the next version but I thing that this may be the issue.

![image](https://user-images.githubusercontent.com/65631811/207137677-dbfcdd9a-808e-4d6b-9bc4-8c8d843f060f.png)

**Comment by Connoropolous** [comment]
Oh ok good to know that you can still access your projects. 

There is an error there that is interesting, if you can click the `>` arrow before the word `type` and fully expand on that error and send that.

**Comment by TechSupport26** [comment]
![image](https://user-images.githubusercontent.com/65631811/207224428-f1714c41-00ac-41ae-91e5-68a583c8f4c5.png)![image](https://user-images.githubusercontent.com/65631811/207224202-3c7f7318-685d-4ab8-b81b-067c7c92bb2a.png)

**Comment by Connoropolous** [comment]
thankyou. I have a useful error message from that, which would be the "CellMissing" error. That will now require a bit of investigation on my part. Thanks for reporting. I will get back to you

**Comment by TechSupport26** [comment]
I am still on this version of Acorn but I was wondering if I should update to the latest version or just stay and wait.

Thanks.

**Comment by TechSupport26** [comment]
To amend an earlier statement, it may have been around the same time that I tried to create an electron application. Is it possible for that to interfere?

**Comment by Connoropolous** [comment]
Hey @TechSupport26 
can you do me a favor, and recap for me: what is your current objective, that you are blocked from? in what way are you blocked?

**Comment by TechSupport26** [comment]
Hi Connoropolous.

My Current objective is to get to the latest version of Acorn but this came up so I am waiting to see if you need anything from my environment. Otherwise, I can run the latest installer file and leave this behind.
I currently have a copy of my projects that I exported just before this happened so upgrading should be fine.

Let me know if there is anything else.

**Comment by Connoropolous** [comment]
Ah I see. Thanks. 
I have encountered one scenario myself dealing with this, but I am not too worried about it as an ongoing issue. 
I propose you just go ahead and install the latest and import your projects :)

**Comment by TechSupport26** [comment]
Thanks Connor.
It is working quite well so I will start mucking about.

Have a good day/night. 😁
