### ISSUE TITLE
Cannot read properties of undefined (reading 'firstName')

### ISSUE THREAD

**Issue by Connoropolous** [lightningrodlabs/acorn#240]
App crash

Reported by @matthme 

```
Cannot read properties of undefined (reading 'firstName')

TypeError: Cannot read properties of undefined (reading 'firstName')
    at EditingOverlay_EditingOverlay (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:121597:132)
    at oh (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:77784:146)
    at di (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:77806:309)
    at Rj (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:77894:406)
    at Qj (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:77877:265)
    at Kj (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:77877:194)
    at yj (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:77870:172)
    at file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:77754:115
    at exports.unstable_runWithPriority (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:80721:467)
    at cg (file:///tmp/.mount_Acorn-CHl3M5/resources/app.asar.unpacked/web/app.js:77753:325)
```

**Comment by Connoropolous** [comment]
maybe duplicate of #262
