### ISSUE TITLE
Simultaneous editing attempt crashes Acorn

### ISSUE THREAD

**Issue by artbrock** [lightningrodlabs/acorn#262]
Cannot read properties of undefined (reading 'firstName')

I think Zippy and I may have tried to edit the same card. Error was as follows...

```
TypeError: Cannot read properties of undefined (reading 'firstName')
    at EditingOverlay_EditingOverlay (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:121597:132)
    at oh (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:77784:146)
    at Rj (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:77892:496)
    at Qj (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:77877:265)
    at Kj (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:77877:194)
    at yj (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:77870:172)
    at file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:77754:115
    at exports.unstable_runWithPriority (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:80721:467)
    at cg (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:77753:325)
    at fg (file:///tmp/.mount_Acorn-27ORcI/resources/app.asar.unpacked/web/app.js:77754:61)
```

**Comment by Connoropolous** [comment]
You should be fine on 'second use'. There can be an issue like that that I've seen during new project member joining, without reload/restart of the app

**Comment by pegahvaezi** [comment]
@Connoropolous still keeping this issue open?
