### ISSUE TITLE
Crash when in update screen

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#276]
V-5.0.2

When you are in the "Your update is prepared" screen, if you refresh acorn will crash.

Cannot read properties of null (reading 'currentVersion')

TypeError: Cannot read properties of null (reading 'currentVersion')
    at file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:124491:55
    at Ii (file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:78166:320)
    at Vj (file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:78212:303)
    at exports.unstable_runWithPriority (file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:81045:467)
    at cg (file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:78077:325)
    at Dj (file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:78212:58)
    at file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:78211:439
    at X (file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:81043:184)
    at H.port1.onmessage (file:///tmp/.mount_Acorn-L3xWEY/resources/app.asar.unpacked/web/app.js:81040:64)

Nothing come up in the terminal that is related to this issue.

### Computer Specs

Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.2
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-6-amd64 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-7500U CPU @ 2.70GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
Manufacturer: Dell Inc.
Product Name: XPS 13 9360

**Comment by pegahvaezi** [comment]
@TechSupport26 are you still experiencing this issue with the newest release (v9.3.1-alpha)?

**Comment by TechSupport26** [comment]
Currently. I get stuck at the Migration warning screen. After closing and opening I get stuck at the same screen.

After deleting the database and keystore file it continues as normal.

I would say close this issue as it is not a full out crash. But log the information somewhere on how to reslove the issue. (deleting the database and keystore files for that version.)
