### ISSUE TITLE
Crash report windows 10

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#329]
I am running windows 10 here and after updating I am no longer able to open acorn. I get to the first loading screen and it gets stuck. Running it from the console gives a bit more info. (See below)
Let me know if you need more information.

Acorn version 8.0.1

This effects other versions of acorn that are installed. I get to the same point with the same crash message.

```shell
C:\Users\Zeph\Desktop>Acorn.lnk

C:\Users\Zeph\Desktop>
ACORN_AGENT_NUM NaN
holochain > Looking for passphrase piped to stdin
holochain > Found passphrase, continuing...
holochain > 1
holochain > WARNING: running without local db encryption
holochain stderr err > WARNING: running without local db encryption

an unhandled error occurred: Error: WARNING: running without local db encryption

    at Socket.<anonymous> (C:\Users\Zeph\AppData\Local\Programs\acorn\resources\app.asar\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[5868:0829/073953.371:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
holochain > # lair-keystore connection_url # named-pipe:\\.\pipe\H5xkpuMCfzKaH-eaFIZoI?k=uKdKIF0fTxSBTBF11n28mKYcsIq7FsOnOiv3ljgBdgg #
holochain > # lair-keystore running #
holochain stderr err > FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        Could not initialize Conductor from configuration: Other({"error":"InternalSodium"}),
    ),
    location: Location {
        file: "src\\embedded_runner.rs",
        line: 109,
        col: 10,
    },
    can_unwind:
an unhandled error occurred: Error: FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        Could not initialize Conductor from configuration: Other({"error":"InternalSodium"}),
    ),
    location: Location {
        file: "src\\embedded_runner.rs",
        line: 109,
        col: 10,
    },
    can_unwind:
    at Socket.<anonymous> (C:\Users\Zeph\AppData\Local\Programs\acorn\resources\app.asar\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
holochain stderr err > true,
}

an unhandled error occurred: Error: true,
}

    at Socket.<anonymous> (C:\Users\Zeph\AppData\Local\Programs\acorn\resources\app.asar\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
holochain stderr err > Well, this is embarrassing.

holochain-runner had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "C:\Users\Zeph\AppData\Local\Temp\report-2526da64-8df6-4353-bb05-b6158af7c8b2.toml". Submit an issue or email with the subject of "holochain-runner Crash Report" and include the report as an attachment.

- Authors: Connor Turland <connor@sprillow.com>, Wesley Finck <wesleyfinck@gmail.com>, Karl Bonnici <karlbonnici100@gmail.com>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

an unhandled error occurred: Error: Well, this is embarrassing.

holochain-runner had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "C:\Users\Zeph\AppData\Local\Temp\report-2526da64-8df6-4353-bb05-b6158af7c8b2.toml". Submit an issue or email with the subject of "holochain-runner Crash Report" and include the report as an attachment.

- Authors: Connor Turland <connor@sprillow.com>, Wesley Finck <wesleyfinck@gmail.com>, Karl Bonnici <karlbonnici100@gmail.com>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!

    at Socket.<anonymous> (C:\Users\Zeph\AppData\Local\Programs\acorn\resources\app.asar\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
holochain >
holochain-runner closed with code:  101

``` 

Report File

```typescript
 
name = "holochain-runner"
operating_system = "Windows 10.0.19045 (Windows 10 Pro) [64-bit]"
crate_version = "0.7.6"
explanation = '''
Panic occurred in file 'src\embedded_runner.rs' at line 109
'''
cause = "Could not initialize Conductor from configuration: Other({\"error\":\"InternalSodium\"})"
method = "Panic"
backtrace = """

   0: 0x7ff7d2d0f549 - <unresolved>
   1: 0x7ff7d2d115c0 - <unresolved>
   2: 0x7ff7d2f4a0b5 - <unresolved>
   3: 0x7ff7d2f4a5c3 - <unresolved>
   4: 0x7ff7d076d93b - <unresolved>
   5: 0x7ff7d0b24bed - <unresolved>
   6: 0x7ff7d094304f - <unresolved>
   7: 0x7ff7d08ff48e - <unresolved>
   8: 0x7ff7d08bb7e6 - <unresolved>
   9: 0x7ff7d08bbb7c - <unresolved>
  10: 0x7ff7d2d00d18 - <unresolved>
  11: 0x7ff7d090017c - <unresolved>
  12: 0x7ff7d2ea3dac - <unresolved>
  13: 0x7ff8399f7614 - BaseThreadInitThunk
  14: 0x7ff839f426b1 - RtlUserThreadStart"""
```

**Comment by Connoropolous** [comment]
so you're saying you could open Acorn v7 before... then you ran v8, then you can't run either?

**Comment by TechSupport26** [comment]
Yes I can't run 7.x.x or higher but I can run versions below 7.x.x

**Comment by Connoropolous** [comment]
can you describe the whole narrative of your updating?

**Comment by TechSupport26** [comment]
This is a vm that I am running so I don't need the information on it.

I updated to v8.0.0 from v7.1.0 using the built in updater. When I ran 8.0.0 everything was fine and projects came across. Then I went to 8.0.1 and I believe from that point I was not able to open Acorn.

I have now removed the data migration file and am now able to get past the initial loading stage. But get stuck at a white screen. I have removed 2 keystore files and databases 10 and 11 and now it is working. I don't have any projects but that is fine.

**Comment by TechSupport26** [comment]
I have gone through the process again and was able to repeat what I did.

When updating I chose to Reset my data and migrate. This is when I am no longer able to open acorn.

See if you can replicate.

**Comment by Connoropolous** [comment]
I think I understand the issue. thank you. We will work on a fix. 

Meanwhile, are you in any need of support?
