### ISSUE TITLE
The "Reload" button returns the same screenshot as attached.

### ISSUE THREAD

**Issue by r-a-i-d** [lightningrodlabs/acorn#344]
![acorn-crash-2023-11-01_13-02-31](https://github.com/lightningrodlabs/acorn/assets/18389593/594be17c-a546-4e51-a701-49785c9b1710)

Hi Team, my first time here!  I'm from Sunshine Coast, Australia!

I'm using Windows 10 - 64-bit operating system, x64-based processor
I was trying to move "outcomes" around on my screen... change the order and nesting...

![acorn-crash2-2023-11-01_13-14-48](https://github.com/lightningrodlabs/acorn/assets/18389593/553d0a68-2cb9-42ef-9f6e-684f96319d07)

As soon as I click on the Project "amUnity Unity Alliance," I get thrown to the "crash" screen, ie as per the first image uploaded.

>> show stack trace...
Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at Array.filter (<anonymous>)
    at getOutcome (file:///C:/Users/Jerard%20Glennon/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103864:14)
    at file:///C:/Users/Jerard%20Glennon/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103866:34
    at Array.map (<anonymous>)
    at getOutcome (file:///C:/Users/Jerard%20Glennon/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103866:14)
    at file:///C:/Users/Jerard%20Glennon/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103866:34
    at Array.map (<anonymous>)
    at getOutcome (file:///C:/Users/Jerard%20Glennon/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103866:14)
    at file:///C:/Users/Jerard%20Glennon/AppData/Local/Programs/acorn/resources/app.asar.unpacked/web/app.js:103866:34
    at Array.map (<anonymous>)

**Comment by TechSupport26** [comment]
Hey. Can you share what version of Acorn you are using?

Thanks.

**Comment by r-a-i-d** [comment]
9.5.1-alpha
I just updated it this morning...

**Comment by Connoropolous** [comment]
hey there! 
let me look into this and see if I can reproduce that. I'm sure that you're right it shouldn't be appearing multiple times there, and then there's the crash.

**Comment by r-a-i-d** [comment]
Hey Connor,
I have created a new test project, which I can open and close.
I cannot open the "amUnity Unity Alliance" project? It goes straight to the "Sorry" screen as above.

When I opened Acorn today, my Virus checker gave me a warning, see two screenshots attached,
I also got this warning on the day of the first issue but did not at that time "Link" the two issues? what do you think?

I went through the automatic cleanup process the first time, to now see the same, it appears, issue today.

![acorn-crash6-2023-11-04_8-53-08](https://github.com/lightningrodlabs/acorn/assets/18389593/584d4c8c-5199-4754-a940-672c81a0cef1)
![acorn-crash5-2023-11-04_8-58-18](https://github.com/lightningrodlabs/acorn/assets/18389593/42541fc8-7c38-4113-8abc-d16081fdd8c4)
![acorn-crash4-2023-11-04_9-09-11](https://github.com/lightningrodlabs/acorn/assets/18389593/d094ccd2-0f31-4b70-9084-85592c29fb6d)
![acorn-crash3-2023-11-04_9-15-18](https://github.com/lightningrodlabs/acorn/assets/18389593/27465e18-2d5d-4560-b0ac-6c0ad3375881)

**Comment by r-a-i-d** [comment]
any updates? thank you

**Comment by Connoropolous** [comment]
hi!

regarding those issues about your virus checker, thats something to raise with the holochain team directly, as that file you referenced is a part of their networking stack. With Acorn we simply bundle holochain basically as-is from what they ship. 

I can actually repost your issue over on their repository to bring it to their attention. 

There is however one thing we do still need to do for better Windows support for Acorn itself and that is to make sure that the application is "signed" with a certificate from Microsoft. we have that on our roadmap to do really soon.

**Comment by Connoropolous** [comment]
are you still encountering issues loading your project?
