### ISSUE TITLE
Acorn crashes on create profile

### ISSUE THREAD

**Issue by shanedeeodonnell** [lightningrodlabs/acorn#82]
I left last name and avatar URL blank. Reload doesn't work. Restart application and reload again all yield the same. Installed the .dmg

Uninstalled and reinstalled and it brought me right back to the Acorn has crashed view.

Stacktrace:

`Cannot read property 'toUpperCase' of undefined

TypeError: Cannot read property 'toUpperCase' of undefined
    at Li (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:351:239552)
    at Zo (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:57951)
    at ws (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:104333)
    at xl (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:96859)
    at bl (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:96784)
    at fl (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:93807)
    at file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:45339
    at t.unstable_runWithPriority (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:317:3844)
    at Va (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:45048)
    at Ja (file:///Applications/Acorn.app/Contents/Resources/app.asar/web/main.js:309:45284)`

**Comment by Connoropolous** [comment]
Oops! For now, just work around it by adding two names. We will work on a fix

**Comment by shanedeeodonnell** [comment]
@pegahvaezi Going to close this. It's been working without issue.
